export const SCREEN_NAME = {
  LANGUAGE_SETUP: 'LanguageSetup',
  MAIN: 'main',
  HOME: 'Home',
  HOME_TAB: 'HomeTab',
  HOME_HISTORY_TAB: 'HomeHistoryTab',
  HOME_FAVORITE_TAB: 'HomeFavoriteTab',
  HOME_MENU_TAB: 'HomeMenuTab',
  CART: 'Cart',
  REGISTER: 'Register',
  LOGIN: 'Login',
  WEB_VIEW: 'WebView',
  ADD_LINK: 'AddProduct',
  TEST: 'test',
};